#!/bin/bash

# ====================================================================
# PHASE 7 MANUAL TESTING - CURL COMMANDS
# ====================================================================

# Replace these with your actual values:
BASE_URL="http://localhost:8000"
API_URL="$BASE_URL/api/v1"
TENANT_ID="47"
CUSTOMER_ID="37"

echo "════════════════════════════════════════════════════════════════════"
echo "🧪 PHASE 7 MANUAL TESTING PROCEDURES"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Total Manual Tests: 8 Endpoints"
echo "Estimated Time: 5-10 minutes"
echo ""

# ====================================================================
# TEST 1: Get Customer Details
# ====================================================================
echo "📌 TEST 1: Get Customer Details"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /customers/{id}"
echo ""
echo "curl -X GET \"$API_URL/customers/$CUSTOMER_ID\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  - id: 37"
echo "  - balance: 0 ✅"
echo "  - total_returns: 2000 ✅"
echo ""

# ====================================================================
# TEST 2: Get Customer Invoices
# ====================================================================
echo "📌 TEST 2: Get Customer Invoices"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /customers/{id}/invoices"
echo ""
echo "curl -X GET \"$API_URL/customers/$CUSTOMER_ID/invoices\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  Invoice #801:"
echo "    - status: 'paid' ✅"
echo "    - grand_total: 2000"
echo "    - paid_amount: 2000"
echo "    - outstanding: 0 ✅"
echo "  Invoice #802:"
echo "    - status: 'closed_by_return' ✅"
echo "    - grand_total: 2000"
echo "    - paid_amount: 2000"
echo "    - outstanding: 0 ✅"
echo ""

# ====================================================================
# TEST 3: Get Customer Account Statement
# ====================================================================
echo "📌 TEST 3: Get Customer Account Statement"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /customers/{id}/statement"
echo ""
echo "curl -X GET \"$API_URL/customers/$CUSTOMER_ID/statement\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  - Should have 3 items (2 invoices + 1 return)"
echo "  - Invoice #801: status = 'paid'"
echo "  - Invoice #802: status = 'closed_by_return'"
echo "  - Return #348: status = 'approved'"
echo ""

# ====================================================================
# TEST 4: Get Customer Ledger
# ====================================================================
echo "📌 TEST 4: Get Customer Ledger (Transaction History)"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /customers/{id}/ledger"
echo ""
echo "curl -X GET \"$API_URL/customers/$CUSTOMER_ID/ledger\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  - Journal Entry #943: Invoice #801 (Debit: 2000, Credit: 2000)"
echo "  - Journal Entry #944: Invoice #802 (Debit: 2000, Credit: 1000)"
echo "  - Journal Entry #945: Return #348 (Debit: 1000, Credit: 2000)"
echo "  - Total Balance: 0 ✅"
echo ""

# ====================================================================
# TEST 5: Get Sales List (All Invoices)
# ====================================================================
echo "📌 TEST 5: Get Sales List"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /sales?customer_id=37"
echo ""
echo "curl -X GET \"$API_URL/sales?customer_id=$CUSTOMER_ID\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  - Invoice #801: status='paid', outstanding=0"
echo "  - Invoice #802: status='closed_by_return', outstanding=0"
echo ""

# ====================================================================
# TEST 6: Get Returns List
# ====================================================================
echo "📌 TEST 6: Get Returns List"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /returns?customer_id=37"
echo ""
echo "curl -X GET \"$API_URL/returns?customer_id=$CUSTOMER_ID\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  - Return #348: status='approved', amount=2000"
echo ""

# ====================================================================
# TEST 7: Get Payments List
# ====================================================================
echo "📌 TEST 7: Get Payments List"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /payments?customer_id=37"
echo ""
echo "curl -X GET \"$API_URL/payments?customer_id=$CUSTOMER_ID\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  - Payment #702: amount=2000, sale_id=801 (for Invoice #801)"
echo "  - Payment #703: amount=1000, sale_id=802 (for Invoice #802)"
echo "  - Payment #704: amount=1000, return_id=348, sale_id=802 (return credit)"
echo ""

# ====================================================================
# TEST 8: Get Account Statement Report
# ====================================================================
echo "📌 TEST 8: Get Account Statement Report"
echo "─────────────────────────────────────────────────────────────────"
echo "Request: GET /accounting/statement?customer_id=37&start_date=2026-05-01&end_date=2026-05-31"
echo ""
echo "curl -X GET \"$API_URL/accounting/statement?customer_id=$CUSTOMER_ID&start_date=2026-05-01&end_date=2026-05-31\" \\"
echo "  -H \"Accept: application/json\" \\"
echo "  -H \"X-Tenant-ID: $TENANT_ID\""
echo ""
echo "Expected Response:"
echo "  - All transactions from May 2026"
echo "  - Correct balance calculations"
echo "  - Invoice statuses updated correctly"
echo ""

echo "════════════════════════════════════════════════════════════════════"
echo "✅ TESTING CHECKLIST"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "For each test, verify:"
echo ""
echo "□ TEST 1: Customer balance = 0 ✅"
echo "□ TEST 1: total_returns = 2000 ✅"
echo ""
echo "□ TEST 2: Invoice #801 status = 'paid' ✅"
echo "□ TEST 2: Invoice #801 outstanding = 0 ✅"
echo "□ TEST 2: Invoice #802 status = 'closed_by_return' ✅"
echo "□ TEST 2: Invoice #802 outstanding = 0 ✅"
echo ""
echo "□ TEST 3: 3 items total (2 invoices + 1 return) ✅"
echo "□ TEST 3: Statuses correctly displayed ✅"
echo ""
echo "□ TEST 4: Journal entries balanced (debit = credit) ✅"
echo "□ TEST 4: Total balance = 0 ✅"
echo ""
echo "□ TEST 5: Both invoices returned ✅"
echo "□ TEST 5: Outstanding = 0 for both ✅"
echo ""
echo "□ TEST 6: Return #348 present ✅"
echo "□ TEST 6: Status = 'approved' ✅"
echo ""
echo "□ TEST 7: 3 payments listed ✅"
echo "□ TEST 7: Payment #704 linked to sale_id=802 ✅"
echo ""
echo "□ TEST 8: All transactions visible ✅"
echo "□ TEST 8: Balances correct ✅"
echo ""

echo "════════════════════════════════════════════════════════════════════"
echo "🎯 WHAT TO LOOK FOR"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ PASS Criteria:"
echo "  • All HTTP status codes = 200 OK"
echo "  • All response bodies contain expected fields"
echo "  • Invoice #801 status = 'paid'"
echo "  • Invoice #802 status = 'closed_by_return'"
echo "  • All outstanding values = 0"
echo "  • Customer balance = 0"
echo "  • Payment #704 correctly linked to invoice #802"
echo ""
echo "❌ FAIL Criteria:"
echo "  • Any HTTP error (4xx, 5xx)"
echo "  • Invoice outstanding > 0"
echo "  • Wrong status values"
echo "  • Missing fields in response"
echo "  • Incorrect payment linkage"
echo ""

echo "════════════════════════════════════════════════════════════════════"
echo "📝 NOTES"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Use Postman or curl to execute these requests"
echo "2. Replace BASE_URL with your actual server URL"
echo "3. Make sure X-Tenant-ID header is set correctly"
echo "4. Total tests: 8 endpoints"
echo "5. Estimated time: 5-10 minutes"
echo "6. If all tests pass: System is production ready ✅"
echo ""
